-- My SQL --
SELECT ROUND(S.LAT_N, 4) 
FROM STATION AS S 
WHERE (SELECT COUNT(LAT_N) FROM STATION WHERE LAT_N > S.LAT_N) = (SELECT COUNT(LAT_N) FROM STATION WHERE LAT_N < S.LAT_N);

-- MS SQL Server -- 
SELECT CAST(ROUND(S.LAT_N, 4) AS DECIMAL(6,4))
FROM STATION AS S 
WHERE (SELECT COUNT(LAT_N) FROM STATION WHERE LAT_N > S.LAT_N) = (SELECT COUNT(LAT_N) FROM STATION WHERE LAT_N < S.LAT_N);
